# Basic of Numpy

In [1]:
import numpy as np


# Use array with datatype int

In [2]:
a = np.array([2,4,5,8],int)

In [3]:
a

array([2, 4, 5, 8])

# You can use dtype = float/int or directly only float/int

# if there have float but select int it will publish all int.
# if there have int but select float all will be float

In [4]:
a = np.array([9,4.5,7,9],dtype=float) 

In [5]:
a

array([9. , 4.5, 7. , 9. ])

# Create 2 dimensional array

In [6]:
b = np.array([[2,3,4,5],[4,8,9,7]])

 # For 2 dimensional array quantity of each dimensional must be same

In [7]:
b

array([[2, 3, 4, 5],
       [4, 8, 9, 7]])

# Find dimension of array

In [8]:
b.ndim

2

# Use ndim for finding array dimension

In [9]:
a.ndim

1

# For finding shape use shape keyword with array

In [10]:
a.shape

(4,)

 # It is 4 because in array a there have 4 int/float

In [11]:
b.shape

(2, 4)

# It is (2,4) because in array b there have 2 rows and 4 columns

# -- Find exact datatype --

In [12]:
a = np.array([2,3,6,7,8,9],dtype='int16')

In [13]:
a

array([2, 3, 6, 7, 8, 9], dtype=int16)

In [14]:
a.dtype

dtype('int16')

In [15]:
a = np.array([2,3,6,7,8,9,4,1,56,34,56],dtype='float64')

#### Must use dtype="float../int.." , use ' ' or " "

In [16]:
a

array([ 2.,  3.,  6.,  7.,  8.,  9.,  4.,  1., 56., 34., 56.])

In [17]:
a.dtype

dtype('float64')

# Find size in array

In [18]:
a.itemsize

8

In [19]:
a.size

11

# ***** Ask trainer the difference between size and itemsize *****

# -- Accessing or changing spacific element --

In [20]:
a = np.array([[1,2,3,4,5],[11,22,32,45,12]])

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [11, 22, 32, 45, 12]])

In [22]:
a[0,3] # 0 for first index (row) and 3 for number 3 index (coloumn)

4

In [23]:
a = np.array([[1,2,3,4,5],[2,5,6,7,4],[9,1,3,23,16]])

In [24]:
a # 3 dimensional array

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16]])

In [25]:
a[2,4]

16

In [26]:
a[1,3] 

7

# a[row index number, column index number]

In [27]:
a[-1,-4]

1

# Accessing a specific column or row

In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16]])

# Find a specific column - First seclect row index number then put :

In [29]:
a[2,:]

array([ 9,  1,  3, 23, 16])

In [30]:
a[-3,:]

array([1, 2, 3, 4, 5])

In [293]:
a = np.array([[1,2,3,4,5],[2,5,6,7,4],[9,1,3,23,16],[10,12,34,54,3]])

In [294]:
a

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16],
       [10, 12, 34, 54,  3]])

In [296]:
a[0:3,0:4]

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 9,  1,  3, 23]])

In [297]:
a[2:4,1:3] # 2:4 for rows and 1:3 for columns (2 start point and 4 end point exclude 4)

array([[ 1,  3],
       [12, 34]])

In [298]:
a

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16],
       [10, 12, 34, 54,  3]])

## When you trun array into boolean

In [299]:
a

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16],
       [10, 12, 34, 54,  3]])

In [300]:
turn_b = a > 20

## If the statement is True the element will be true rather False

In [301]:
turn_b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False,  True,  True, False]])

In [303]:
turn_b = a < 4/2

In [304]:
turn_b

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

# Find a column with stepsize

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 2,  5,  6,  7,  4],
       [ 9,  1,  3, 23, 16]])

In [32]:
a[0, 1:4:2]

array([2, 4])

In [33]:
b = np.array([3,5,7,8,1,6,9])

In [34]:
b

array([3, 5, 7, 8, 1, 6, 9])

In [35]:
b = np.array([[3,5,7,8,1,6,9],[8,5,6,98,2,3,1],[23,56,78,12,3,4,7]])

In [36]:
b

array([[ 3,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 12,  3,  4,  7]])

# b[index number, starting column index number : ending column index number : stepsize]

In [37]:
b[2,3:6:1]

array([12,  3,  4])

# Replace any element 

In [38]:
b

array([[ 3,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 12,  3,  4,  7]])

# b[row index number, column index number] = value

In [39]:
b[2,3] = 15

In [40]:
b

array([[ 3,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 15,  3,  4,  7]])

In [41]:
b[0,0] = 10 

# Row index number 0 and column index number 0

In [42]:
b

array([[10,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 15,  3,  4,  7]])

# Select any column or specific column

In [43]:
b[:1] # Row index is blank that means there have o , it should be write like b[0:1]

array([[10,  5,  7,  8,  1,  6,  9]])

In [44]:
# Row index number : that means it will show all the rest including index number 1

In [45]:
b[1:] 

array([[ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 15,  3,  4,  7]])

In [46]:
b

array([[10,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 15,  3,  4,  7]])

# Here : mean all rows and 2 is for column index number, number will be same for that index


In [47]:
b[:,2] = 10

In [48]:
b

array([[10,  5, 10,  8,  1,  6,  9],
       [ 8,  5, 10, 98,  2,  3,  1],
       [23, 56, 10, 15,  3,  4,  7]])

In [49]:
b[:,6] = [5,1,3]

In [50]:
 # Must write equal quantity of index number if you want to show different number for different index

In [51]:
b

array([[10,  5, 10,  8,  1,  6,  5],
       [ 8,  5, 10, 98,  2,  3,  1],
       [23, 56, 10, 15,  3,  4,  3]])

# Create 3-D array

In [52]:
a = np.array([[[19,10,4,2],[12,56,32,1]],[[9,4,1,7],[2,4,7,8]]])

In [53]:
print(a)

[[[19 10  4  2]
  [12 56 32  1]]

 [[ 9  4  1  7]
  [ 2  4  7  8]]]


# Here 0 index is [[[19 10  4  2]  [12 56 32  1]] and 1 is second index of 0 index array
 

In [54]:
a[0,1,2]

32

# 0  = first index and 1 = first index of 0 index, 2 = column index of 1 number index

In [55]:
a[0,1,:3]

array([12, 56, 32])

In [56]:
# :3 means it will show before elements of index 3 including 3

In [57]:
a

array([[[19, 10,  4,  2],
        [12, 56, 32,  1]],

       [[ 9,  4,  1,  7],
        [ 2,  4,  7,  8]]])

In [58]:
a[1,1,3]

8

In [59]:
a[1,0,1:]

array([4, 1, 7])

In [60]:
a[0:]

array([[[19, 10,  4,  2],
        [12, 56, 32,  1]],

       [[ 9,  4,  1,  7],
        [ 2,  4,  7,  8]]])

In [61]:
a[:1] # Except the 1 index number it will show before elements

array([[[19, 10,  4,  2],
        [12, 56, 32,  1]]])

In [62]:
a[:]

array([[[19, 10,  4,  2],
        [12, 56, 32,  1]],

       [[ 9,  4,  1,  7],
        [ 2,  4,  7,  8]]])

# Show full columns of number 1 index in both arrays

In [63]:
a[:,1,:]

array([[12, 56, 32,  1],
       [ 2,  4,  7,  8]])

In [64]:
a[:,0,:]

array([[19, 10,  4,  2],
       [ 9,  4,  1,  7]])

In [65]:
a

array([[[19, 10,  4,  2],
        [12, 56, 32,  1]],

       [[ 9,  4,  1,  7],
        [ 2,  4,  7,  8]]])

In [66]:
a[:,0,2]

array([4, 1])

In [67]:
a[:,1,3]

array([1, 8])

# Replace with new numbers

In [68]:
a[:,1,3] = [4,5]

In [69]:
a

array([[[19, 10,  4,  2],
        [12, 56, 32,  4]],

       [[ 9,  4,  1,  7],
        [ 2,  4,  7,  5]]])

# -- Inilialize different types of array -- NP.ZEROS

In [70]:
a = np.zeros(6)

In [71]:
# You can mention it int or float like np.zeros(6,int/float)

In [72]:
a

array([0., 0., 0., 0., 0., 0.])

In [149]:
a = np.zeros((3,4,3))

In [74]:
# 2 is coloum quantity and 3 is row quantity

In [150]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# -- Inilialize different types of array -- NP.ONES

In [76]:
a = np.ones((3,2,4),dtype='int32') # 3 = row and 2 = column

In [77]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

# Add any number 

In [78]:
a = np.full((3,2),33)

In [79]:
# 3 = row count, 2 cols count and 33 inplace of 1

In [80]:
a

array([[33, 33],
       [33, 33],
       [33, 33]])

In [81]:
np.full((5,11),2, dtype="float32")

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]], dtype=float32)

In [82]:
np.full((3,6),5, float)

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

In [83]:
a

array([[33, 33],
       [33, 33],
       [33, 33]])

In [84]:
a = np.full_like(a,4)

# Convert the remain number with new same number

# np.full_like(array name, the number you want to replace)

In [85]:
a

array([[4, 4],
       [4, 4],
       [4, 4]])

# -- Show Random numbers -- 

In [86]:
a = np.random.rand()

In [87]:
a

0.9807715692622172

##### In random function all numbers are less that 1 (one)

In [88]:
a = np.random.rand(2,3)

In [89]:
a

array([[0.29196259, 0.55701744, 0.25897869],
       [0.3284004 , 0.85190541, 0.64155861]])

#### If you use 'rand' the number should be less than 1 and positive

In [90]:
np.random.rand(2,3,6) 

array([[[0.85593669, 0.97131554, 0.7550915 , 0.24763502, 0.99467113,
         0.3480977 ],
        [0.50559331, 0.65710205, 0.28766985, 0.26579362, 0.03911403,
         0.24632996],
        [0.70678362, 0.89382644, 0.86705904, 0.25700062, 0.18185633,
         0.94130351]],

       [[0.40033379, 0.0489441 , 0.14118194, 0.10510349, 0.92112964,
         0.47424247],
        [0.11166059, 0.85077454, 0.06386442, 0.24885264, 0.18709201,
         0.46991318],
        [0.35756796, 0.48338701, 0.15808265, 0.69068406, 0.36714865,
         0.99081243]]])

In [91]:
b = np.random.randint(6, size=(3,4))

### If you need a between numbers like (3-10 exclude 10) must use 'randint'

In [92]:
# 6 = ( 0 to 5 exlude 6), 3 cols 4 rows

In [93]:
b

array([[4, 2, 1, 4],
       [0, 4, 5, 0],
       [3, 2, 3, 2]])

In [94]:
b = np.random.randint(5,20, size=(5,8))

In [95]:
b

array([[ 5, 17, 12, 16, 11, 13, 11, 17],
       [12, 14, 13, 10,  5,  9, 13, 10],
       [18, 18, 10, 16, 17, 15,  6, 19],
       [16, 18, 19, 11,  8, 16, 15, 18],
       [16,  9, 18, 19, 17,  6,  5, 12]])

In [96]:
b = np.random.randint(-7,20, size=(5,8))

In [97]:
b

array([[ 9,  1, 19,  2,  5, -1,  0, 14],
       [ 3,  7, -3, -3, 19, -1, 13,  8],
       [ 1, 18, -5, -6, -4,  5, 19, -3],
       [-7, -5, -5,  8, -6,  4, -5,  3],
       [-4, -5,  3,  3,  6, -6,  6, -3]])

In [167]:
a = np.random.rand(3,6,4)

# 3 = dimension/matrix, 6 = rows, 4 = columns

In [168]:
a

array([[[0.89924197, 0.87132083, 0.96383255, 0.42155331],
        [0.02268425, 0.81810318, 0.31182139, 0.34770872],
        [0.29268957, 0.13672846, 0.53556615, 0.39955474],
        [0.65797303, 0.32664331, 0.04694559, 0.57678341],
        [0.39626274, 0.74443453, 0.37857545, 0.20305173],
        [0.92650651, 0.95547508, 0.54035337, 0.94718201]],

       [[0.11946632, 0.32239857, 0.06602564, 0.5942269 ],
        [0.38778187, 0.75961955, 0.3308926 , 0.2022531 ],
        [0.72929757, 0.46941713, 0.95139255, 0.98606685],
        [0.01731812, 0.21792162, 0.48905252, 0.15342142],
        [0.67467119, 0.52765805, 0.37821523, 0.56227099],
        [0.98073169, 0.41294964, 0.709369  , 0.95883699]],

       [[0.57919689, 0.29380979, 0.96688086, 0.48892873],
        [0.16480459, 0.75234937, 0.03485915, 0.00385751],
        [0.96882417, 0.75441034, 0.42482826, 0.50184259],
        [0.88650976, 0.33450811, 0.49555363, 0.41031971],
        [0.71381549, 0.6828458 , 0.89220144, 0.63108412],
        [0

In [169]:
a = np.random.randn(2,5,4)

#### If you use 'randn' the number should be more than 1 and it may be positive or negative

In [170]:
a

array([[[-2.6377187 ,  0.39931372, -0.94393377,  0.69555782],
        [ 1.35732116, -1.09839025, -0.06223388, -1.32988951],
        [-0.96732135, -0.95521749,  1.11901131, -0.34270258],
        [ 1.63092141,  1.13096055,  1.61439387,  0.14842692],
        [-0.63881194, -1.36761886,  0.97557337, -0.31704372]],

       [[-0.52845959, -0.06574972,  0.03783784, -0.53071379],
        [ 0.13312543, -1.02865402,  0.44099309,  0.50955208],
        [ 0.68408845,  0.53601411,  1.46187441,  0.40916821],
        [ 1.40769589,  0.28826549,  0.29495194, -1.24426298],
        [-0.7439134 ,  0.13179591, -1.63025845, -0.10023158]]])

# -- The Identitical matrix --

In [98]:
a = np.identity(4, dtype='int')

In [99]:
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

###### # you can use eye or identity for identitical matrix

In [100]:
a = np.eye(5)

In [101]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
a = np.eye(9,dtype="int")

In [103]:
a

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

# -- Use linspace --

In [117]:
a = np.linspace(1,15)

In [118]:
# np.linspace(start point, end point, total parts)


# If you don't put the number of total parts, numpy will create 50 parts automatically

In [119]:
a

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [124]:
a = np.linspace(1,10,5, dtype="int")

In [125]:
a

array([ 1,  3,  5,  7, 10])

# Use arange in numpy

In [ ]:
# a = np.arange(start point, end point, step size)

In [126]:
a = np.arange(1,20,3)

In [ ]:
# if there is no step size it will show 1 - 19

In [128]:
print(a)


[ 1  4  7 10 13 16 19]


In [129]:
a = np.arange(6,30)

In [130]:
a

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

### Use logspace in numpy

In [140]:
a = np.logspace(1,23,10)

##### # 10 is total parts here

In [141]:
a

array([1.00000000e+01, 2.78255940e+03, 7.74263683e+05, 2.15443469e+08,
       5.99484250e+10, 1.66810054e+13, 4.64158883e+15, 1.29154967e+18,
       3.59381366e+20, 1.00000000e+23])

In [142]:
a[0]

10.0

In [143]:
a[6]

4641588833612792.0

###### # After dot(.) how many numbers you want to show
    use ('%.4f' %a[index number]) 
    4 = total numbers after dot(.) f = float

In [147]:
print('%.4f' %a[5])

16681005372000.6250


#### Create array from list in numpy

In [151]:
a  = [4,67,23,1,90,3]

In [155]:
arr = np.array(a)

In [156]:
arr

array([ 4, 67, 23,  1, 90,  3])

In [157]:
# Create 2 D array from list
# Must the element per list should be equal quantity

a = [[2,4,5,6,3],[9,2,5,7,1]]
np.array(a)

array([[2, 4, 5, 6, 3],
       [9, 2, 5, 7, 1]])

#### Create Diagonal matrix in numpy

In [161]:
a = np.diag([4,5,8]) # 3 elements here for this we can 3 columns 3 rows

In [162]:
a

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 8]])

In [163]:
a = np.diag([12,34,56,78])

In [164]:
a

array([[12,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0, 78]])

## Find elements with shape

In [176]:
a  = np.array([4,67,23,1,90,3])


In [ ]:
# Total elements is 6

In [177]:
a.shape

(6,)

In [178]:
a = np.diag([12,34,56,78])

In [179]:
a

array([[12,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0, 78]])

### 4 columns and 4 rows

In [180]:
a.shape

(4, 4)

In [182]:
a.dtype

dtype('int32')

## Find location in memory

In [183]:
a.data

In [187]:
b = np.array([2,4,5,7])
b.data

## Array Indexing in numpy

In [214]:
a = np.linspace(2,3,6)

In [215]:
# For linspace don't use []

In [216]:
a

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

##### end = ' ' it may be space or anything

In [222]:
for i in a:
    print(i, end = ' ')

2.0 2.2 2.4 2.6 2.8 3.0 

In [221]:
for i in a:
    print(i, end = '|')

2.0|2.2|2.4|2.6|2.8|3.0|

In [225]:
b = np.array([[3,5,7,8,1,6,9],[8,5,6,98,2,3,1],[23,56,78,12,3,4,7]])

In [226]:
b

array([[ 3,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 12,  3,  4,  7]])

In [246]:
for arr in b:
    print(arr, end = ',')

[3 5 7 8 1 6 9],[ 8  5  6 98  2  3  1],[23 56 78 12  3  4  7],

## Second way for printing index

In [235]:
b

array([[ 3,  5,  7,  8,  1,  6,  9],
       [ 8,  5,  6, 98,  2,  3,  1],
       [23, 56, 78, 12,  3,  4,  7]])

In [242]:
a = np.linspace(2,3,6)

In [243]:
a

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [244]:
for m in range(len(a)):
    print(m, end = ',')

0,1,2,3,4,5,

## ReShape function in numpy

In [251]:
a = np.array([[2,4,5,6],[6,7,8,9],[2,5,8,4],[20,1,5,13]])

In [252]:
a

array([[ 2,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 2,  5,  8,  4],
       [20,  1,  5, 13]])

In [253]:
a.shape

(4, 4)

#### Before go to ReShape must shape it and check the countability

##### The numbers of shape (4 multiply 4) = 16 which must be same 16 at reshape ( it may be like (8 multiply 2))

In [254]:
a.reshape(2,8)

array([[ 2,  4,  5,  6,  6,  7,  8,  9],
       [ 2,  5,  8,  4, 20,  1,  5, 13]])

# Use 'ravel' function in numpy

### It is used to make 2 or 3 dimensional array in 1 dimensional array

In [255]:
a

array([[ 2,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 2,  5,  8,  4],
       [20,  1,  5, 13]])

In [257]:
a.ravel()

array([ 2,  4,  5,  6,  6,  7,  8,  9,  2,  5,  8,  4, 20,  1,  5, 13])

# Arithmetic in numpy

In [258]:
a = np.arange(1,20)

In [259]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [260]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [261]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [262]:
a*a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [263]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

## 0/0 is undefined if there is any index of 0

In [265]:

a = np.arange(0,20)

In [266]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [267]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [269]:
 # a/a , that means 0/0 = nan which is undefined

## If the 2 array's dimension are not same

In [270]:
a = np.array([[2,4,5,6],[6,7,8,9],[2,5,8,4],[20,1,5,13]])

In [271]:
a

array([[ 2,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 2,  5,  8,  4],
       [20,  1,  5, 13]])

In [272]:
a.shape

(4, 4)

In [274]:
b = a.reshape(8,2)

In [275]:
b

array([[ 2,  4],
       [ 5,  6],
       [ 6,  7],
       [ 8,  9],
       [ 2,  5],
       [ 8,  4],
       [20,  1],
       [ 5, 13]])

### In this situaton make 2 arrays same dimension like both must be (8 multiply 2) or (4 multiply 4)

In [278]:
b = b.reshape(4,4)

In [279]:
b

array([[ 2,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 2,  5,  8,  4],
       [20,  1,  5, 13]])

In [280]:
a+b

array([[ 4,  8, 10, 12],
       [12, 14, 16, 18],
       [ 4, 10, 16,  8],
       [40,  2, 10, 26]])

In [281]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [282]:
a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [283]:
a*b

array([[  4,  16,  25,  36],
       [ 36,  49,  64,  81],
       [  4,  25,  64,  16],
       [400,   1,  25, 169]])

## If you need to sum following row or column

In [284]:
c = a+b

In [285]:
c

array([[ 4,  8, 10, 12],
       [12, 14, 16, 18],
       [ 4, 10, 16,  8],
       [40,  2, 10, 26]])

### axix = 0, it is for rows

In [286]:
c.sum(axis=0)

array([60, 34, 52, 64])

### axis = 1 , it is for columns

In [287]:
c.sum(axis=1)

array([34, 60, 38, 78])